### ISSUE TITLE
Peligro de paths!

### ISSUE THREAD

**Issue by devedetti** [trifulca/panflix#1]
https://github.com/trifulca/panflix/blob/4def613820ff609abafe8abc3c9e45bc6ec2f86f/panflix.py#L19

Esto es un peligro! la función path.join está mal hecha, si llegás a meter un '/tuvieja' pisa todo lo previo

```python
In [4]: join('/home/nachopro', '/etc/passwd')
Out[4]: '/etc/passwd'
```

**Comment by hugoruscitti** [comment]
mire el comentario de la linea 17 señor:

https://github.com/trifulca/panflix/blob/4def613820ff609abafe8abc3c9e45bc6ec2f86f/panflix.py#L17

**Comment by devedetti** [comment]
Estaría bueno que Github genere tickets a raíz de los TODOs

**Comment by hugoruscitti** [comment]
Bueno, al final pasamos todo a nodejs... no se si esto sigue siendo un problema, creo que no.
Lo cierro, cualquier cosa abrimos otro issue.
